name: capstone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dialogflow_grpc: ^0.2.9
  rxdart: ^0.24.1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.3.2
  google_sign_in: ^5.2.1
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
    - assets/images/
